### ISSUE TITLE
Todo

### ISSUE THREAD

**Issue by ZeleffOff** [ZeleffOff/discord-blindtest#1]
## 📝 Todo List

- [ ] Possibility of customizing the blindtest embeds. (round cooldown, win, score)
- [ ] Ability to filter users authorized to play.
- [ ] Possibility of doing blindtests with images.
- [ ] Make the game more flexible by deciding whether to allow what type of information gives points or not. (author, title, featuring)
